version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: zyplow_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: